### ISSUE TITLE
The hardware has only 7 volume levels

### ISSUE THREAD

**Issue by Simsys** [larus-breeze/sw_bluepill_sound_and_GPIO#1]
As you can easily see in the schematic, the resistor network in set_volume() is controlled by 6 port pins. A total of 7 volume levels are available: 6 individually controlled and the seventh when all ports are switched simultaneously.

The software implementation in pieps.cpp suggests 8 volume levels.

Since the implementation is scattered and not encapsulated, this also affects audiocontroller.cpp lines 192 - 194 and 262.

Overall, one should be honest: There are seven volume levels: 0..7: 0 off and 1-7 the seven levels. Anything set above that should be clamped at 7.

The current implementation: mapping 20 virtual levels to 7 real levels only confuses.

**Comment by realtimepeople** [comment]
Upgraded to 16 levels.
